### ISSUE TITLE
Dynamically registered BroadcastReceiver

### ISSUE THREAD

**Issue by JordanSamhi** [secure-software-engineering/FlowDroid#173] opened 2019-06-27 12:24 UTC
As you may know, broadcast receivers can be registered dynamically in an Android app so it does not necessarily appear in the manifest file. (As far as I know this is the only component able to do that).
I experienced a case where such a component was therefore invisible to Flowdroid (just the modelling part, I do not use the flow analysis). So my analysis cannot perform those components, it is a pity because those are the interesting ones.
So my question is : Does Flowdroid currently model components dynamically registered with "registerReceiver()" method for example or it only detect them in the manifest file ?

**Comment by StevenArzt** [comment] 2019-06-27 12:43
FlowDroid should be able to find calls to the ```registerReceiver()``` method in the code as part of its callback analysis. If that doesn't work, it might be a bug. Can you have a look at method ```analyzeMethodForDynamicBroadcastReceiver()``` in class ```AbstractCallbackAnalyzer```?

**Comment by dusby** [comment] 2019-06-27 14:51
Sure, I will have a look and I will keep you informed.

**Comment by zjbthomas** [comment] 2019-06-30 19:13
@dusby Did you enable IccTA? I think it may be a bug of IccTA. At line 111 to 115 of IccRedirectionCreator.java, if a component is not defined in the manifest, there is no redirect method for it. I had this issue before and a dynamically registered BroadcastReceiver also suffers from this issue.

**Comment by dusby** [comment] 2019-07-02 18:40
In fact, the problem is not due to the non-detection of the registerReceiver, so it is not a bug. It is simpley the same problem as #171.
PR #177 fixes the problem.

**Comment by StevenArzt** [comment] 2019-11-08 16:18
Since the problem is fixed now, I close this issue.

**Closed by StevenArzt** 2019-11-08 16:18 UTC
