### ISSUE TITLE
call graph is incomplete

### ISSUE THREAD

**Issue by ws1994** [secure-software-engineering/FlowDroid#166] opened 2019-05-31 02:28 UTC
Hey, I want to get a complete call graph that contain all method in the apk. But the call graph I get is usually incomplete. For example, some network-related APIs has no caller.And sometimes I can not find some methods. It is confusing. Can you tell me the key options I should set? or is there a guide book I can refer to?  I need your help. Thank you a lot.

**Comment by ShengliangD** [comment] 2019-05-31 15:35
I'm also facing this problem, any suggestions?

**Comment by StevenArzt** [comment] 2019-06-03 08:48
This issue seems to be a duplicate of #167. Let's merge these discussions. I take #167 as the primary one, because it is more specific.

**Closed by StevenArzt** 2019-06-03 08:48 UTC
