### ISSUE TITLE
Can we use this tool for analysing large apps, if so what are the system configurations required? 

### ISSUE THREAD

**Issue by trickerkaim** [secure-software-engineering/FlowDroid#48] opened 2018-06-25 09:46 UTC
I am trying to use flowdroid on my system with apps like facebook, whatsapp etc. Mostly taint analysis never completes and if complete gives an error Like this: 

`[pool-1-thread-3] ERROR heros.solver.IDESolver - Worker thread execution failed: soot.RefType cannot be cast to soot.ArrayType
java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
        at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:352)
        at soot.jimple.infoflow.problems.InfoflowProblem$1.access$600(InfoflowProblem.java:290)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:645)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargets(InfoflowProblem.java:475)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:35)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:402)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:58)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:511)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at heros.solver.CountLatch.awaitZero(CountLatch.java:75)
        at heros.solver.CountingThreadPoolExecutor.awaitCompletion(CountingThreadPoolExecutor.java:67)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:192)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:173)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:149)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:407)
        at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:266)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(Unknown Source)
        at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Unknown Source)
        at soot.jimple.infoflow.android.TestApps.Test.main(Unknown Source)
Exception in thread "pool-1-thread-3" java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
        at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:352)
        at soot.jimple.infoflow.problems.InfoflowProblem$1.access$600(InfoflowProblem.java:290)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:645)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargets(InfoflowProblem.java:475)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:35)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:402)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:58)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:511)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.RuntimeException: There were exceptions during IDE analysis. Exiting.
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.runExecutorAndAwaitCompletion(IFDSSolver.java:198)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.awaitCompletionComputeValuesAndShutdown(IFDSSolver.java:173)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.solve(IFDSSolver.java:149)
        at soot.jimple.infoflow.Infoflow.runAnalysis(Infoflow.java:407)
        at soot.jimple.infoflow.Infoflow.computeInfoflow(Infoflow.java:266)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(Unknown Source)
        at soot.jimple.infoflow.android.TestApps.Test.runAnalysis(Unknown Source)
        at soot.jimple.infoflow.android.TestApps.Test.main(Unknown Source)
Caused by: java.lang.ClassCastException: soot.RefType cannot be cast to soot.ArrayType
        at soot.jimple.infoflow.problems.InfoflowProblem$1.addTaintViaStmt(InfoflowProblem.java:352)
        at soot.jimple.infoflow.problems.InfoflowProblem$1.access$600(InfoflowProblem.java:290)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargetsInternal(InfoflowProblem.java:645)
        at soot.jimple.infoflow.problems.InfoflowProblem$1$2.computeTargets(InfoflowProblem.java:475)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:76)
        at soot.jimple.infoflow.solver.fastSolver.InfoflowSolver.computeNormalFlowFunction(InfoflowSolver.java:35)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.processNormalFlow(IFDSSolver.java:402)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver.access$100(IFDSSolver.java:58)
        at soot.jimple.infoflow.solver.fastSolver.IFDSSolver$PathEdgeProcessingTask.run(IFDSSolver.java:511)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

i.e. IFDS solver fails

**Comment by StevenArzt** [comment] 2018-06-26 09:51
According to the line numbers in the stack trace, you are not using the most recent version of FlowDroid. Can you reproduce the issue with the current code from the "develop" branch?

**Comment by StevenArzt** [comment] 2018-08-17 09:48
I close this issue because there has not ben any further feedback. Please create a new issue in case the issue still exists with the newest version of FlowDroid.

**Closed by StevenArzt** 2018-08-17 09:48 UTC
